require conf/distro/poky.conf

DISTRO = "sensornode"
DISTRO_NAME = "Stonetusker SensorNode"
DISTRO_VERSION = "0.3"
DISTRO_CODENAME = "blueprint"

DISTRO_FEATURES:append = " systemd usrmerge ipv4 ipv6"
DISTRO_FEATURES:remove = " x11 wayland pulseaudio bluetooth nfc"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""
VIRTUAL-RUNTIME_login_manager = "shadow-base"

PACKAGE_CLASSES ?= "package_ipk"
EXTRA_IMAGE_FEATURES ?= ""
INHERIT += "buildhistory"
BUILDHISTORY_COMMIT = "0"

# Release builds override this with the Git-derived artifact identity.
SENSORNODE_IMAGE_VERSION ?= "${DISTRO_VERSION}-${DATETIME}"
