BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "sensornode"
BBFILE_PATTERN_sensornode = "^${LAYERDIR}/"
BBFILE_PRIORITY_sensornode = "8"

LAYERSERIES_COMPAT_sensornode = "scarthgap"
LAYERDEPENDS_sensornode = "core openembedded-layer"
