header:
  version: 14

machine: qemuarm64
distro: sensornode
target:
  - sensornode-image-dev

repos:
  poky:
    url: https://git.yoctoproject.org/poky
    commit: scarthgap
    layers:
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url: https://github.com/openembedded/meta-openembedded.git
    commit: scarthgap
    layers:
      meta-oe:
      meta-networking:
      meta-python:

  meta-sensornode:
    path: .
    layers:
      meta-sensornode:

local_conf_header:
  common: |
    CONF_VERSION = "2"
    BB_NUMBER_THREADS ?= "6"
    PARALLEL_MAKE ?= "-j 6"
    DL_DIR ?= "${TOPDIR}/../cache/downloads"
    SSTATE_DIR ?= "${TOPDIR}/../cache/sstate"
    TMPDIR = "${TOPDIR}/tmp"
    INHERIT += "buildstats"
    USER_CLASSES ?= "buildstats"
    BB_UNSHARE_NET = "0"

    # 1. On-demand pre-compiled task cache (falls back to local build if missing)
    SSTATE_MIRRORS = "file://.* http://host.docker.internal:9000/yocto-sstate/PATH"
    
    # 2. On-demand source tarball cache (falls back to public Internet if missing)
    PREMIRRORS:prepend = "\
        git://.*/.*     http://host.docker.internal:9000/yocto-downloads/ \n \
        ftp://.*/.*     http://host.docker.internal:9000/yocto-downloads/ \n \
        http://.*/.*    http://host.docker.internal:9000/yocto-downloads/ \n \
        https://.*/.*   http://host.docker.internal:9000/yocto-downloads/ \n"


